//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdditionalRSVP
    {
        public int AdditionalRSVPId { get; set; }
        public int RSVPId { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        [Required]
        [Display(Name = "Adult or Child")]
        public string Adult { get; set; }

        [Required]
        public string StarterChoice { get; set; }

        [Required]
        public string DieatryRequirements { get; set; }

        [MaxLength(2500)]
        public string DietaryRequirementsDetails { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual RSVP RSVP { get; set; }
    }
}
